### ISSUE TITLE
Inconsistent naming between FEStateOptions and FiniteElementState

### ISSUE THREAD

**Issue by white238** [LLNL/serac#276]
We should be consistent one way or the other.

**Comment by samuelpmish** [comment]
It looks like FEStateOptions exists for the sole purpose of appearing as the second argument in the FiniteElementState constructor. If that's all it does, it feels like it should be defined inside the FiniteElementState,

https://godbolt.org/z/v5j6z6
```cpp
struct Mesh{};

struct FiniteElementState{
    struct Options{
        int a;
        double b;
    };
    FiniteElementState(Mesh m, Options opt){}
};

int main() {
    FiniteElementState state(Mesh{}, {.a = 1, .b = 3.14});
}
```

On an unrelated note, it also looks like we may not need to explicitly name the FiniteElementState::Options type in the constructor to use the designated initializer syntax

**Comment by joshessman-llnl** [comment]
> 
> It looks like FEStateOptions exists for the sole purpose of appearing as the second argument in the FiniteElementState constructor. If that's all it does, it feels like it should be defined inside the FiniteElementState,
> 

I agree, though this actually relates to a compiler bug I found earlier present on both [GCC](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=88165) and [Clang](https://bugs.llvm.org/show_bug.cgi?id=36684).

In this case we can work around it by setting the defaults as an init-list in the FEState constructor instead of via non-static data member initialization.

It also looks like Clang is able to deduce the type of the designated initializer, but GCC is not: https://dev.azure.com/llnl-serac/serac/_build/results?buildId=2072&view=logs&j=87099fe3-114b-5988-d488-711793d65ea3&t=59402ce6-cdf6-5dd4-ed7b-a626fb7cd080
