### ISSUE TITLE
Investigate casting issues

### ISSUE THREAD

**Issue by jamiebramwell** [LLNL/serac#384]
is it worth it to just define `sample_vectors` to take a `size_t` or whatever `state.range(0)` is, rather than static casting everything to `int`?

_Originally posted by @samuelpmishLLNL in https://github.com/LLNL/serac/pull/363#discussion_r574170321_

**Comment by jamiebramwell** [comment]
Tagging @jonwong12 as he is also running into a similar issue.

**Comment by joshessman-llnl** [comment]
Just a followup to the comment in #363 - I had initially tried something like this but because MFEM uses `int` for all its size types it's easier to stay with `int` as much as possible.  Google Benchmark uses the `size_t` for its sizes (which I personally prefer) but anything that uses MFEM classes is more or less required to use `int`.

**Comment by jamiebramwell** [comment]
That makes sense. I just wanted to make sure there isn't another fancier thing we could be doing.
