### ISSUE TITLE
Use value semantics for the mesh

### ISSUE THREAD

**Issue by jamiebramwell** [LLNL/serac#406]
My preference here would be to have the `buildMeshFromFile` etc functions return an `mfem::Mesh` instead of a smart pointer (since they have no need to be on the heap), but for consistency that would require changing all the other signatures, which I was planning on doing when making all the other shapes available through Inlet.

_Originally posted by @joshessman-llnl in https://github.com/LLNL/serac/pull/398#discussion_r584713987_

**Comment by joshessman-llnl** [comment]
This is a little messier than anticipated; I didn't realize that `mfem::Mesh` marks its copy constructor as `explicit`.  This precludes statements like `return m;` (which qualifies for NRVO) and forces us to do `return mfem::Mesh(m);` which does **not** qualify for NRVO.  One option would be to add a move constructor to MFEM, which (even if explicit) should let us avoid the full copy.

**Comment by jandrej** [comment]
Relevant https://github.com/mfem/mfem/pull/2054

**Comment by pazner** [comment]
Just to jump in on this discussion, once mfem/mfem#2016 is merged, `Mesh` and `ParMesh` should have move constructors (and assignment operators) that will allow you to return `Mesh` objects by value.

In most cases, the compiler will be able to perform a move elision, so that it would be equivalent to constructing the mesh in place. Even in cases where the compiler can't elide the move, it will still be a very cheap operation.

**Comment by jamiebramwell** [comment]
Awesome! Thanks @pazner ! That will clean up a bunch of our code.
