### ISSUE TITLE
Using two different CMake versions between Serac and using-with-cmake causes failures

### ISSUE THREAD

**Issue by white238** [LLNL/serac#513]
Caliper treats their CUDAToolKit targets differently depending on which CMake version you are using.  Therefore on CMake > 3.17, we have to call `find_package(CUDAToolKit)`.

This can cause a confusing error if you build Serac with CMake >3.17 then build the `using-with-cmake` example with CMake <3.17.

Without looking into this, Caliper should probably fix this on their installed config files to call `find_package(CUDAToolKit)`.

**Comment by white238** [comment]
I added some more clear and earlier failures but further hardening should happen.

**Comment by joshessman-llnl** [comment]
I'm almost inclined to say that these "surgical" checks like the one recently added:

https://github.com/LLNL/serac/blob/a839f8dc1560b1ec2b3d542f23a5f2ac71f2a962/cmake/thirdparty/SetupSeracThirdParty.cmake#L171

 are preferable to something that restricts users to the exact same CMake version that Serac was built with, especially because I think these cases are fairly rare
