### ISSUE TITLE
Add restart integration tests

### ISSUE THREAD

**Issue by white238** [LLNL/serac#655]
Add a new optional parameter in `tolerance_test` to handle restart tests.

Something like this:

```
tolerance_test(name="dyn_exp_solve_serial",
    input_file="some_input.lua",
    restart_cycle="10")
```

Then the test workflow would be this:

```
serac -i some_input.lua  // this runs fully
serac -i some_input --restart-cycle=10  // restarts previous run on cycle 10
// run tolerance_test.py against last summary file and baseline
```

If the restart_cycle parameter is not given it should not run the second serac command like it is currently.

**Comment by chapman39** [comment]
I believe this may involve changing serac's `-c` option. It seems to be looking for a file called something like `default_datacoll_000001.root` in the directory specified in `-o`. But when I run serac without `-c`, this `.root` file is only _sometimes_ created.

I may be able to simply check if these datacoll files are created before running serac with the `-c` option, but I'm not sure if you'd want that. Plus, the restarted serac run's output will likely override the previous serac run, since the `-o` option seems to be for both checking the datacoll files as well as the serac run's output.

Also, I'm not sure if the `-c` option works, since if I run it with a test that does have datacoll files (such as `dyn_imp_solve_restart`), it will always begin at step 1 even if I specify `-c` as 4, for example. But I haven't verified this - it might just be printing the previous steps.
